#!/bin/bash

MAXIRQ=$1

echo "//Making table for $MAXIRQ interrupts"

for (( c=0; c<=$MAXIRQ; c++ ))
do
  echo "stub( $c );"
done

echo "Handler VectorTable[] __attribute__((section(\".vectors.3\"))) = {"

for (( c=0; c<=$MAXIRQ; c++ ))
do
  echo "IrqName( $c ),"
done


echo "};"



